# 
control_dt: 0.02

msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "/home/mycode/ASAP/deploy/pre_train/g1_21/model_27200.onnx"
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"

action_joint2motor_idx: [0, 1, 2, 3, 4, 5, 
                        6, 7, 8, 9, 10, 11,
                        12, 
                        15, 16, 17, 18,
                        22, 23, 24, 25]
kps: [100, 100, 100, 200, 20, 20, 
      100, 100, 100, 200, 20, 20, 
      400, 
      90,   60,  20, 60, 
      90,   60,  20, 60 ]
kds: [2.5, 2.5, 2.5, 5.0, 0.2, 0.1, 
      2.5, 2.5, 2.5, 5.0, 0.2, 0.1, 
      5.0, 
      2.0, 1.0, 0.4, 1.0, 
      2.0, 1.0, 0.4, 1.0 ]

default_angles: [ -0.1, 0.0, 0.0, 0.3, -0.2, 0.0, 
                  -0.1, 0.0, 0.0, 0.3, -0.2, 0.0, 
                  0.0, 
                  0.0, 0.0, 0.0, 0.0, 
                  0.0, 0.0, 0.0, 0.0 ]

fixed_joint2motor_idx: [13, 14,
                        19, 20, 21,
                        26, 27, 28]

fixed_kps: [400, 400,
                20, 20, 20,
                20, 20, 20]

fixed_kds: [5, 5, 
            1, 1, 1,
            1, 1, 1]
fixed_target: [0, 0, 0, 0, 0, 0, 0, 0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25

ref_motion_phase : 0.00314

# cmd_scale: [2.0, 2.0, 0.25]
num_actions: 21
num_obs: 350

# max_cmd: [0.8, 0.5, 1.57]



history_length : 4
